---
to: <%= rootDirectory %>/app/layout.tsx
force: true
---
import React from 'react';
import { Metadata } from 'next';
import {AppHeader} from '@/components/common/AppHeader';
<%_ if (project.plugins.find(p => p.name === 'auth')?.enable) { -%>
import {Auth} from '@/components/common/Auth';
<%_ } -%>
import {AppDialog} from '@/components/modal/AppDialog';
import {AppLoading} from '@/components/modal/AppLoading';
import {AppSnackbar} from '@/components/modal/AppSnackbar';
import theme from '@/styles/theme';
import {Box, CssBaseline, Toolbar} from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import '@/lib/axios';

export const metadata: Metadata = {
  title: '<%= project.name %>',
  description: 'Generated by Next.js App Router',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
<%_ if (project.plugins.find(p => p.name === 'auth')?.enable) { -%>
            <Auth>
              <Box sx={{display: 'flex'}}>
                <AppHeader />
                <Box component="main" sx={{flexGrow: 1}}>
                  <Toolbar variant="dense" />
                  {children}
                </Box>
                <AppDialog />
                <AppLoading />
                <AppSnackbar />
              </Box>
            </Auth>
<%_ } else { -%>
            <Box sx={{display: 'flex'}}>
              <AppHeader />
              <Box component="main" sx={{flexGrow: 1}}>
                <Toolbar variant="dense" />
                {children}
              </Box>
              <AppDialog />
              <AppLoading />
              <AppSnackbar />
            </Box>
<%_ } -%>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
} 